- styles.css
The updated design adds a hover effect to the logo, enhances link hover colors, and improves dropdown visibility with shadows for depth. It makes the navigation bar responsive with a toggleable hamburger menu on smaller screens. The CSS includes smoother transitions for a modern look, and JavaScript toggles the menu visibility on mobile.
>  i change footer and navbar 

- index.html
- styles.css
Pull Request: Fixed Issue #6 - Removed White Space Above Navigation Bar
Description:
This pull request addresses Issue #6 by removing the unwanted white space above the navigation bar in our web application. The presence of this extra space was causing layout issues and negatively affecting the overall user experience.
Changes Made:
Adjusted the CSS styles responsible for the spacing above the navigation bar, eliminating the unwanted white space.
Verified that the navigation bar now aligns properly with the top of the viewport, providing a cleaner and more cohesive look to the website's header section.
Ensured that all related components maintain their intended spacing and layout.
Made necessary adjustments to address Issue #20, enhancing the overall layout and functionality.
Testing: …
> Navigation padding issue

- index.html
i have made the logos clearly visible in the website!!
> Updated Icons In the code social website

- .vscode/settings.json
- README.md
- darkmode.js
- index.html
- styles.css
#36
please add the labels of level2, gssoc-ext and hacktoberfest before closing this pr
> added event calendar and dark mode on the top right corner

- index.html
- script.js
Logo Path Update , Dropdown Structure Fix , Hamburger Menu Toggle Button , Alt Tags for Images , Linking the JavaScript File , Dropdown Functionality , Hamburger Menu Toggle , Optimized Navbar Toggle for Small Screens #59 
More Responsive: The hamburger menu works well for mobile screens.
Cleaner Dropdowns: Dropdown menus are only displayed when hovering over their parent items.
More User-Friendly: Improved usability for both mobile and larger screens.
> HTML Changes, Script.js Changes

- index.html
- styles.css
- Added a label "Pick color for event:" for the event color picker in the "Add Event" form.
- Enhanced user experience by making the color picker more intuitive and descriptive.
- Adjusted the alignment of text elements in the navbar to ensure consistent spacing and positioning.
- Before 
- After
https://github.com/user-attachments/assets/e815083d-8b19-4a3e-83ac-32037e809af7
Please assign gssoc-ex and hacktoberfest labels to this PR
> Enhanced Event Calendar

- index.html
- styles.css
Reverts Code-Social/official-website#158
> Revert "Enhanced Event Calendar"

- styles.css
This PR refines the event form's user interface by applying modern styling and adding interactive elements. The form now features better spacing, padding, and a rounded, shadowed container for a polished look. The color picker has been customized to match the form's aesthetic, with added hover and focus animations, making the interface more engaging. These updates provide a more user-friendly and visually appealing experience, enhancing the overall interaction with the form.
> Improved Event Form UI with Enhanced Styling and Animated Color Picker

- index.html
Updatd Favicon in the web page!!
> Updated Favicon in the website

- index.html
- learning.html
> Added Learning section

- styles.css
Hello,
Fixed issue - #220 
Issue fixed  -
> Fixed text color issue ! #220

- 404.html
- index.html
- maintenance.html
- script.js
Hello, PR
Fixed issue number - #222
These four images(2 website logo, dark mode & light mode icon image) are not loading in Header & Footer, but now I fixed this issue properly -
https://github.com/user-attachments/assets/9dc4e8e1-abd2-495b-8f42-79f5fc381f7d
> Fixed images not loading issue ! #222

- blog.html
- index.html
- learning.html
- login.html
- maintenance.html
- mentorship.html
- signup.html
- volunteering-oppurtunities/volunteer-opp-page.html
#269 solved , the chatbot is working.
https://github.com/user-attachments/assets/ef35e3b8-fc55-4693-b9e3-d2490c8bc484
@Rizwan102003  . @SaurabhS55 @pulkitpathak99 can you please review this , thank you.
> ✨chatbot added ✨

- darkmode.js
- index.html
Reviewers: @SaurabhS55 @pulkitpathak99
> fix: correct image loading for toggle button in light/dark mode

- maintenance.html
Fixes #302 
Reviewers: @pulkitpathak99
> fix: logo image path fix in maintenance.html

- blog.css
- blog.html
- index.html
- styles.css
hey @Rizwan102003 I have updated the design of blog page.  Just take a look and let me know if there anything else you want.
Please make sure to add labels gssoc-ext, hactoberfest, level1, level2, level3.
> blog page updated

- styles.css
> Text visible now in Event title #321

- Resources.css
- Resources.html
- index.html
- styles.css
This PR implements the "Resources" feature for students, which I believe includes high-quality, free resources that will help students get started in tech.
Fixes #308 
- Added resources for various tech domains.
- Each resource includes the language and its corresponding link.
- Mentioned the instructor's name for each resource.
- Cleaned up the UI, added a hover effect for better UX on the resource links.
- Included only top-rated resources to ensure quality.
In a previous PR, I worked on the footer section. However, while resolving merge conflicts, some code was accidentally deleted. This PR also restores and corrects the footer code.
> [Feat]- Student Tech Resources and Footer Fix 

- index.html
#326 
This pull request introduces a trailing cursor effect to improve user interaction and create a more dynamic interface. The effect follows the user's mouse movement, providing a visually engaging experience that complements the overall design.
https://github.com/user-attachments/assets/0e84bc1a-c65e-4f1b-9d09-b566a77e04bf
> Added a trailing cursor effect for enhanced user interaction

- blog.css
- blog.html
The icons and the content written in footer part of blogs are now aligned in better way.
> Bug331 solved

- learning.html
Hey @Rizwan102003  I have updated learning page. Just take a look, and let me know If anything else do you want to change.
Before: (Light Mode)
Before: ( Dark Mode)
After: (Light Mode)
After: (Dark Mode) 
If you like it, make sure to add  the labels gssoc-ext, hactoberfest, level2, or level3.
> update learning page

- index.html
- register.html
- #361 
When the user went to the live events section there was no option for registration for live events. So I went ahead and added an option for users to register themselves for any live event. The user can enter their name and email to get themselves registered.
https://github.com/user-attachments/assets/6078f00f-e3b6-4ad2-a6b3-148a835606b6
> [FIXED] Feature: Adding a registration page for live events #361

- darkmode.js
- index.html
- styles.css
closes #363 
https://github.com/user-attachments/assets/cecfaf58-1f20-4e44-8bf6-eda283292ebf
> fixed dark mode toggle for footer section

- index.html
- styles.css
Issue #344 
Hi @Rizwan102003 ,I have made changes where the "Code Social" written in header is visible in dark mode also I have added animation to the title, increased the size of logo and hover effects to the tabs.
https://github.com/user-attachments/assets/90893daa-e902-48cf-9c8b-b3bb19a914b0
Check if the changes are according to your liking and please accept the pull request and let me know if changes are to be made.
Thank you!
> "Code Social" written in header not visible in dark mode

- index.html
- styles.css
This PR enhances the calendar functionality by enabling the addition and display of multiple events on a single date.
-fix issue #384 
-feature request 
[Screencast from 2024-10-25 00-28-58.webm](https://github.com/user-attachments/assets/42e2c5dc-56fc-4fcb-ac6f-a2b448ce84c3)
> [feat]Allow Adding Multiple Events on a Single Date in Calendar

- index.html
https://github.com/user-attachments/assets/dd702610-8045-43e3-b478-da21447aaba7
> Enhanced the UI of Webpage by making changes in it .

- learning.html
https://github.com/user-attachments/assets/1b4ef3dc-2166-46b8-8a8a-7616f2ae79da
> Adding trailing cursor in learning page 

- learning.html
- login.html
- signup.html
I will be really grateful if you can assign me the Level 3 label for the Gssoc
https://github.com/user-attachments/assets/2b683fe8-ef73-4210-bf2e-5ea3090c03a8
> Added the trailing effect int he login page and the signup page 

- index.html
Fixing up a small issue in the code
> Correcting index.html

- index.html
> Disable and restrict 'Add Event' button for past dates

- index.html
- maintenance.html
- Closes #382 
- The darkmode.js is written such that it requires both navbar and footer for the dark mode toggle to work. Thus. added footer to maintenance.html. 
- Also, corrected the path of logo in footer of index page
- Reviewers: @Saurabhchaudhary9799 @pulkitpathak99 @Rizwan102003 
- OS [macOS]
- Browser [Chrome]
> fix: dark mode enabled in maintenance.html

- Resources.html
Added navbar and footer, which also now supports dark and light mode switch
Screenshots:
https://github.com/user-attachments/assets/28d7d813-9245-437c-a53c-bbb989db7d5a
OS [macOS]
Browser [Chrome]
> feat: added navbar and footer to Resources.html

- styles.css
I have successfully changed the color of the links. 
Issue resolved: #170
> color changed

- darkmode.js
- index.html
- styles.css
issue #402 
Redesign the toggle button with minimal  modern style 
before --
after --
@protonerdy see this & merge it !!! 
@arushi2610
> change the theme toogle button with modern style button

- JoinTeam.css
- JoinTeam.html
- index.html
**Description:**
This pull request introduces a new "Join Our Team" page to our project. The page is designed to encourage community members to join our tech team and participate in our open-source initiatives. The following features have been implemented
fixes #431 
1.A responsive layout using HTML and CSS.
2.A header section that provides a brief introduction.
3.A grid layout showcasing the benefits of joining our community.
4.A call-to-action link that directs users to the Google Form for joining the team.
**Screenshot**
> [Feat]-Join Our Team Page Added

- index.html
Chatbot Icon overlaps with Scroll to top button #421 has been solved
> Chatbot Icon overlaps with Scroll to top button #421
